/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewMDIApplication.java
 *
 * Created on 04-dic-2010, 19:13:42
 */

package managerrrhhhospital;

import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;

/**
 *
 * @author Manuel
 */
public class uiPrincipal extends javax.swing.JFrame {

    /** Creates new form NewMDIApplication */
    public uiPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _dskPanel = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        _mnuCategorias = new javax.swing.JMenuItem();
        _mnuUsuarios = new javax.swing.JMenuItem();
        _mnuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setText("Opciones de Sistema");

        _mnuCategorias.setText("Gestion de Categorías");
        fileMenu.add(_mnuCategorias);

        _mnuUsuarios.setText("Gestion de Usuarios");
        fileMenu.add(_mnuUsuarios);

        _mnuExit.setText("Salir");
        _mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _mnuExitActionPerformed(evt);
            }
        });
        fileMenu.add(_mnuExit);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_dskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_dskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__mnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event__mnuExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane _dskPanel;
    private javax.swing.JMenuItem _mnuCategorias;
    private javax.swing.JMenuItem _mnuExit;
    private javax.swing.JMenuItem _mnuUsuarios;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getDskPanel() {
        return _dskPanel;
    }

    public JMenuItem getMnuCategorias() {
        return _mnuCategorias;
    }

    public JMenuItem getMnuExit() {
        return _mnuExit;
    }

    public JMenuItem getMnuUsuarios() {
        return _mnuUsuarios;
    }

}
